resource "local_file" "pet" {
  filename = "filename"
  content  = "content"
}

# resource "random_pet" "my-pet" {
# prefix= "Mrs"
# separator = "."
# length = "3"
# }
output "pet-name" {
value = local_file.pet.id
description = "Record the value of pet ID generated by the random_pet resource"
}